services:
  # Backend Web Service
  - type: web
    name: outbound-ai-backend
    runtime: node
    plan: starter
    region: oregon
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && node server.js
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://krishjain:Krish%40123@cluster0.v7ckm.mongodb.net/outbound-ai-mvp?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        value: https://outbound-ai-frontend.vercel.app
      - key: BACKEND_URL
        value: https://outbound-ai-backend.onrender.com
      - key: TELNYX_API_KEY
        sync: false
      - key: TELNYX_PHONE_NUMBER
        sync: false
      - key: TELNYX_CONNECTION_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_VOICE_ID
        value: pNInz6obpgDQGcFmaJgB

databases:
  - name: outboundaimongodb
    databaseName: outboundaimvp
    user: outboundaiuser
    plan: starter
    region: oregon
